[project]
name = "wx-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.115.12",
    "ibm-watsonx-ai>=1.3.24",
    "langgraph>=0.4.8",
    "mcp[cli]>=1.9.4",
]
